export const ADMIN_CONSTANTS = {
    ADMIN_LOGIN_REQUEST: 'ADMIN_LOGIN_REQUEST',
    ADMIN_LOGIN_SUCCESS: 'ADMIN_LOGIN_SUCCESS',
    ADMIN_LOGIN_FAIL: 'ADMIN_LOGIN_FAIL',
    ADMIN_LOGOUT: 'ADMIN_LOGOUT',

    ADMIN_GET_REQUEST: 'ADMIN_GET_REQUEST',
    ADMIN_GET_SUCCESS: 'ADMIN_GET_SUCCESS',
    ADMIN_GET_FAIL: 'ADMIN_GET_FAIL',

    ADMIN_DETAIL_REQUEST: 'ADMIN_DETAIL_REQUEST',
    ADMIN_DETAIL_SUCCESS: 'ADMIN_DETAIL_SUCCESS',
    ADMIN_DETAIL_FAIL: 'ADMIN_DETAIL_FAIL'

}