export const ADMIN_CONSTANTS = {
    ADMIN_LOGIN_REQUEST: 'ADMIN_LOGIN_REQUEST',
    ADMIN_LOGIN_SUCCESS: 'ADMIN_LOGIN_SUCCESS',
    ADMIN_LOGIN_FAIL: 'ADMIN_LOGIN_FAIL',
    ADMIN_LOGOUT: 'ADMIN_LOGOUT',

    ADMIN_PROFILE_REQUEST: 'ADMIN_PROFILE_REQUEST',
    ADMIN_PROFILE_SUCCESS: 'ADMIN_PROFILE_SUCCESS',
    ADMIN_PROFILE_FAIL: 'ADMIN_PROFILE_FAIL',
  
    ADMIN_UPDATE_REQUEST: 'ADMIN_UPDATE_REQUEST',
    ADMIN_UPDATE_SUCCESS: 'ADMIN_UPDATE_SUCCESS',
    ADMIN_UPDATE_FAIL: 'ADMIN_UPDATE_FAIL',

    ADMIN_PASSWORD_REQUEST: 'ADMIN_PASSWORD_REQUEST',
    ADMIN_PASSWORD_SUCCESS: 'ADMIN_PASSWORD_SUCCESS',
    ADMIN_PASSWORD_FAIL: 'ADMIN_PASSWORD_FAIL',
  

    ADMIN_GET_REQUEST: 'ADMIN_GET_REQUEST',
    ADMIN_GET_SUCCESS: 'ADMIN_GET_SUCCESS',
    ADMIN_GET_FAIL: 'ADMIN_GET_FAIL',

    ADMIN_DETAIL_REQUEST: 'ADMIN_DETAIL_REQUEST',
    ADMIN_DETAIL_SUCCESS: 'ADMIN_DETAIL_SUCCESS',
    ADMIN_DETAIL_FAIL: 'ADMIN_DETAIL_FAIL'

}