export const CARD_LIST_REQUEST= 'CARD_LIST_REQUEST'
export const CARD_LIST_SUCCESS= 'CARD_LIST_SUCCESS'
export const CARD_LIST_FAIL= 'CARD_LIST_FAIL'

export const CARD_DETAIL_REQUEST= 'CARD_DETAIL_REQUEST'
export const CARD_DETAIL_SUCCESS= 'CARD_DETAIL_SUCCESS'
export const CARD_DETAIL_FAIL= 'CARD_DETAIL_FAIL'

