export const TRANSACTION_CONSTANTS = {
    TRANSACTION_ALL_REQUEST: 'TRANSACTION_ALL_REQUEST',
    TRANSACTION_ALL_SUCCESS: 'TRANSACTION_ALL_SUCCESS',
    TRANSACTION_ALL_FAIL: 'TRANSACTION_ALL_FAIL',


    TRANSACTION_DETAIL_REQUEST: 'TRANSACTION_DETAIL_REQUEST',
    TRANSACTION_DETAIL_SUCCESS: 'TRANSACTION_DETAIL_SUCCESS',
    TRANSACTION_DETAIL_FAIL: 'TRANSACTION_DETAIL_FAIL',
}

export const CARD_CONSTANTS = {
    CARD_ALL_REQUEST: 'CARD_ALL_REQUEST',
    CARD_ALL_SUCCESS: 'CARD_ALL_SUCCESS',
    CARD_ALL_FAIL: 'CARD_ALL_FAIL',

    CARD_DEACTIVE_REQUEST: 'CARD_DEACTIVE_REQUEST',
    CARD_DEACTIVE_SUCCESS: 'CARD_DEACTIVE_SUCCESS',
    CARD_DEACTIVE_FAIL: 'CARD_DEACTIVE_FAIL',

    CARD_ACTIVE_REQUEST: 'CARD_ACTIVE_REQUEST',
    CARD_ACTIVE_SUCCESS: 'CARD_ACTIVE_SUCCESS',
    CARD_ACTIVE_FAIL: 'CARD_ACTIVE_FAIL',
}

