export const ORDER_CONSTANTS = {
    ORDER_INIT_REQUEST: 'ORDER_INIT_REQUEST',
    ORDER_INIT_SUCCESS: 'ORDER_INIT_SUCCESS',
    ORDER_INIT_FAIL: 'ORDER_INIT_FAIL',
    ORDER_INIT_RESET: 'ORDER_INIT_RESET',
}

