export const USER_CONSTANTS = {
    USER_LOGIN_REQUEST: 'USER_LOGIN_REQUEST',
    USER_LOGIN_SUCCESS: 'USER_LOGIN_SUCCESS',
    USER_LOGIN_FAIL: 'USER_LOGIN_FAIL',
    USER_LOGOUT: 'USER_LOGOUT',

    USER_REGISTER_REQUEST: 'USER_REGISTER_REQUEST',
    USER_REGISTER_SUCCESS: 'USER_REGISTER_SUCCESS',
    USER_REGISTER_FAIL: 'USER_REGISTER_FAIL',

    USER_DETAILS_REQUEST: 'USER_DETAILS_REQUEST',
    USER_DETAILS_SUCCESS: 'USER_DETAILS_SUCCESS',
    USER_DETAILS_FAIL: 'USER_DETAILS_FAIL',

    USER_UPDATE_PASS_REQUEST: 'USER_UPDATE_PASS_REQUEST',
    USER_UPDATE_PASS_SUCCESS: 'USER_UPDATE_PASS_SUCCESS',
    USER_UPDATE_PASS_FAIL: 'USER_UPDATE_PASS_FAIL',

    USER_GET_PAYMENT_REQUEST: 'USER_GET_PAYMENT_REQUEST',
    USER_GET_PAYMENT_SUCCESS: 'USER_GET_PAYMENT_SUCCESS',
    USER_GET_PAYMENT_FAIL: 'USER_GET_PAYMENT_FAIL',

    USER_SUB_PAYMENT_REQUEST: 'USER_SUB_PAYMENT_REQUEST',
    USER_SUB_PAYMENT_SUCCESS: 'USER_SUB_PAYMENT_SUCCESS',
    USER_SUB_PAYMENT_FAIL: 'USER_SUB_PAYMENT_FAIL',

    USER_WITHDRAW_REQUEST: 'USER_WITHDRAW_REQUEST',
    USER_WITHDRAW_SUCCESS: 'USER_WITHDRAW_SUCCESS',
    USER_WITHDRAW_FAIL: 'USER_WITHDRAW_FAIL',
}

